backend:
  name: github
  repo: USERNAME/wow-drama24
  branch: main
  auth_scope: repo

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "dramas"
    label: "Drama List"
    files:
      - file: "src/data/dramas.json"
        label: "Dramas"
        name: "dramas"
        fields:
          - name: list
            label: List
            widget: list
            fields:
              - { name: title, label: Title, widget: string }
              - { name: slug, label: Slug, widget: string }
              - { name: poster, label: Poster, widget: image }
              - { name: category, label: Category, widget: list }
              - { name: tmdb_id, label: TMDB ID, widget: string }
              - { name: year, label: Year, widget: number }
